core:
  cluster-api:
    namespace: capi-system
    createNamespace: false

bootstrap:
  kubeadm:
    namespace: capi-kubeadm-bootstrap-system
    createNamespace: false

controlPlane:
  kubeadm:
    namespace: capi-kubeadm-control-plane-system
    createNamespace: false

infrastructure:
  metal3:
    namespace: capm3-system
    createNamespace: false

addon: {}
# helm: {}                # Name, required
#   namespace: ""         # Optional
#   version: ""           # Optional
#   createNamespace: true # Optional
#   deployment:           # Optional
#     replicas: 1
#     nodeSelector: {}
#     tolerations: []
#     affinity: {}
#     containers: []
#     serviceAccountName: ""
#     imagePullSecrets: []
#   manager:              # Optional
#     metrics:
#       insecureDiagnostics: true
#       diagnosticsAddress: localhost:8080

ipam: {}
# in-cluster: {}          # Name, required
#   namespace: ""         # Optional
#   version: ""           # Optional
#   createNamespace: true # Optional
#   deployment:           # Optional
#     replicas: 1
#     nodeSelector: {}
#     tolerations: []
#     affinity: {}
#     containers: []
#     serviceAccountName: ""
#     imagePullSecrets: []
#   manager:              # Optional
#     featureGates:
#       ClusterTopology: true
#     metrics:
#       insecureDiagnostics: true
#       diagnosticsAddress: localhost:8080

enableHelmHook: false
