webContext: /sealed-secrets

ingress:
  enabled: true
  # className: ingress-nginx
  hosts:
    - host: localhost
      paths:
        - path: /sealed-secrets
          pathType: ImplementationSpecific
