webContext: /sealed-secrets

# ingress:
#   enabled: true
#   className: traefik
#   annotations:
#     traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-prefix@kubernetescrd
#   hosts:
#     - host: localhost
#       paths:
#         - path: /sealed-secrets(/|$)(.*)
#           pathType: ImplementationSpecific

### extras ###
extras: {}
