# webContext: /sealed-secrets

ingress:
  enabled: true
  className: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: /sealed-secrets(/|$)(.*)
          pathType: ImplementationSpecific
