# alertmanager:
#   ingress:
#     enabled: true
# prometheus:
#   thanosIngress:
#     enabled: true
#   ingress:
#     enabled: true

# --web.external-url and --web.route-prefix options.
# For example, set:
#   --web.external-url="https://yourdomain.com/alertmanager/"
#   --web.route-prefix="/"

grafana:
  grafana.ini:
    server:
      domain: localhost
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      serve_from_sub_path: true

  adminPassword: admin # TODO: Migrate me to sealed secrets!

prometheus:
  prometheusSpec:
    additionalArgs:
      - name: web.external-url
        value: /prometheus/
      - name: web.route-prefix
        value: /prometheus/

extraManifests:
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: '{{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "alertmanager" }}'
    spec:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - localhost
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /alertmanager
          filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  type: ReplacePrefixMatch
                  replacePrefixMatch: /
          backendRefs:
            - group: ""
              kind: Service
              name: '{{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "alertmanager" }}'
              port: 9093
              weight: 1
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: '{{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" }}'
    spec:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - localhost
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /prometheus
          # filters:
          #   - type: URLRewrite
          #     urlRewrite:
          #       path:
          #         type: ReplacePrefixMatch
          #         replacePrefixMatch: /
          backendRefs:
            - group: ""
              kind: Service
              name: '{{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" }}'
              port: 9090
              weight: 1
  # - apiVersion: gateway.networking.k8s.io/v1
  #   kind: HTTPRoute
  #   metadata:
  #     name: '{{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "thanos-gateway" }}'
  #   spec:
  #     parentRefs:
  #       - group: gateway.networking.k8s.io
  #         kind: Gateway
  #         name: traefik-gateway
  #         namespace: traefik
  #     hostnames:
  #       - localhost
  #     rules:
  #       - matches:
  #           - path:
  #               type: PathPrefix
  #               value: /thanos-gateway
  #         backendRefs:
  #           - group: ''
  #             kind: Service
  #             name: '{{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "thanos-discovery" }}'
  #             port: 10901
  #             weight: 1
  - apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: '{{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "grafana" }}'
    spec:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: traefik-gateway
          namespace: traefik
      hostnames:
        - localhost
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /grafana
          backendRefs:
            - group: ""
              kind: Service
              name: '{{ printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "grafana" }}'
              port: 80
              weight: 1
